# Generated by ChatGPT for DocSeva feature upgrade
import uuid
from django.db import migrations, models


def populate_emergency_tokens(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    for profile in UserProfile.objects.filter(emergency_token__isnull=True):
        profile.emergency_token = uuid.uuid4()
        profile.save(update_fields=['emergency_token'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_subscriptionplan_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_portal_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_token',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(populate_emergency_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_share_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_doctor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='renewal_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('needs_review', 'Needs review'), ('renewal_started', 'Renewal started'), ('renewed', 'Renewed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='renewal_notes',
            field=models.TextField(blank=True),
        ),
    ]
