# Generated by DocSeva upgrade patch.
import uuid
from django.db import migrations, models


def populate_share_tokens(apps, schema_editor):
    Document = apps.get_model('core', 'Document')
    for doc in Document.objects.filter(share_token__isnull=True):
        token = uuid.uuid4()
        while Document.objects.filter(share_token=token).exists():
            token = uuid.uuid4()
        doc.share_token = token
        doc.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portal_admin_emergency_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='share_token',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.RunPython(populate_share_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='document',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AddField(
            model_name='document',
            name='share_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='share_download_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='share_expires_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='share_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='share_message',
            field=models.CharField(max_length=240, blank=True),
        ),
    ]
