# Generated by DocSeva role separation upgrade.
from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    for profile in UserProfile.objects.select_related('user'):
        if getattr(profile.user, 'is_superuser', False):
            profile.portal_role = 'superadmin'
            profile.is_portal_admin = True
        elif profile.is_portal_admin:
            profile.portal_role = 'admin'
        else:
            profile.portal_role = 'user'
        profile.save(update_fields=['portal_role', 'is_portal_admin'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_document_public_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portal_role',
            field=models.CharField(
                choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')],
                default='user',
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_roles, migrations.RunPython.noop),
    ]
